name=PropertiesConfig
property.filename = logs
appenders = console, file

# Console Appender - Logs WARN level and above
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# File Appender - Logs INFO level and above
appender.file.type = File
appender.file.name = LOGFILE
appender.file.fileName=${filename}/propertieslogs.log
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# Root logger configuration
rootLogger.level = info
rootLogger.appenderRefs = stdout, file

# Console logs WARN and above
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.stdout.level = info

# File logs INFO and above
rootLogger.appenderRef.file.ref = LOGFILE
rootLogger.appenderRef.file.level = info

## Set package-specific log levels
#loggers=com.myaccount
#
## Specify the log level for com.myaccount package
#logger.com.myaccount.name=com.myaccount
#logger.com.myaccount.level = info
#logger.com.myaccount.appenderRefs = console, file
#logger.com.myaccount.appenderRef.console.ref = STDOUT
#logger.com.myaccount.appenderRef.file.ref = LOGFILE